import { ARCHETYPES, ARCHETYPE_LABELS } from "@/game/archetypes";
import { MIDWEEK, PPM } from "@/game/midweek/config";
import { HABITS, type SimStats, type Target } from "./midweek-world";

/**
 * Renders docs/archive/MIDWEEK_TUNING.md, the tuning sign-off artifact
 * (BUILD_SPEC §44.12). It is regenerated by every full `npm run sim:midweek`,
 * so anything that should survive a regeneration lives here, not in the file.
 */

const x = (ppm: number) => (ppm / PPM).toFixed(3);
const pct = (v: number) => `${(v * 100).toFixed(1)}%`;

const STARTING: Array<[string, string, () => string]> = [
  ["OVR factor at OVR 83", "1.35", () => x(MIDWEEK.ovr.factorMaxPpm)],
  [
    "Form roll range (mode 1.00)",
    "0.75–1.45",
    () => `${x(MIDWEEK.form.minPpm)}–${x(MIDWEEK.form.maxPpm)}`,
  ],
  [
    "Pick factor curve",
    "(0, 1.30) (0.40, 1.00) (1, 0.85)",
    () => MIDWEEK.pick.points.map(([s, f]) => `(${x(s)}, ${x(f)})`).join(" "),
  ],
  ["Day roll", "±0.10", () => `±${x(MIDWEEK.dayRollSpreadPpm)}`],
  ["Injured fitness", "0.95", () => x(MIDWEEK.injuredFitnessPpm)],
  ["Auto-squad factor", "0.65", () => x(MIDWEEK.autoFactorPpm)],
  ["Trialist OVR", "30", () => String(MIDWEEK.trialist.ovr)],
  ["Trialist factor (new)", "—", () => x(MIDWEEK.trialist.factorPpm)],
  [
    "Line values for 0 / 1 / 2 / 3 plusses: attack (new, ADR-116)",
    "—",
    () => MIDWEEK.shape.attPpm.map(x).join(" / "),
  ],
  ["… midfield (new, ADR-116)", "—", () => MIDWEEK.shape.midPpm.map(x).join(" / ")],
  ["… defence (new, ADR-116)", "—", () => MIDWEEK.shape.defPpm.map(x).join(" / ")],
  [
    "Weakest-line rule (new, ADR-116)",
    "—",
    () =>
      `${MIDWEEK.balance.minPlusses} plusses per line, ×${x(MIDWEEK.balance.shortfallPpm)} per plus short`,
  ],
  ["Goalkeeper in goal (new, ADR-116)", "1.650 (from the offsets)", () => x(MIDWEEK.keeperPpm)],
  [
    "Keeperless: the stand-in's share of a Goalkeeper's strength",
    "0.60 of its own defence line",
    () => x(MIDWEEK.keeperlessFactorPpm),
  ],
  [
    "Outfield defence's weight in a shot's resistance (new, ADR-116)",
    "0.50 (the keeper had the other half)",
    () => x(MIDWEEK.match.defenceWeightPpm),
  ],
  ["Shoot-out sudden-death cap", "20", () => String(MIDWEEK.penalties.maxSuddenDeathRounds)],
  [
    "Chance slots × chance rate (new)",
    "—",
    () => `${MIDWEEK.match.chanceSlots} × ${x(MIDWEEK.match.chanceRatePpm)}`,
  ],
  [
    "Midfield / finishing contrast (new)",
    "—",
    () => `${MIDWEEK.match.midfieldContrast} / ${MIDWEEK.match.finishingContrast}`,
  ],
  ["Goal base probability (new)", "—", () => x(MIDWEEK.match.goalBasePpm)],
  ["Win-chance contrast (new)", "—", () => String(MIDWEEK.winChanceContrast)],
];

const NOTES = `## Trade-offs for the sign-off

**ADR-092 (signed off 2026-09-25):** the owner accepted the first and third
rows as they were (70.6% and 58.7%), so their bands pass up to 72% and from
58%. **ADR-116 (MM 2.0 C2)** retunes with the weekly rotation on, the plusses
as the engine's input and the weakest-line rule, against the same bands plus
the two shape rows.

- **Wealth against thinking.** The first and third rows still pull against
  each other. The weakest collection in a KUT-shaped club is almost always a
  starter pack: three cards and two trialists, and trialists are All-rounders,
  so it often falls short in a line. Balance is now the main edge of thinking,
  and it also helps the strongest collection, which has the most to choose
  from. The flatter OVR factor and the stand-in keeper pay for that.
- **What a "thought-through" pick is.** The simulated thinker fields a
  Goalkeeper if it owns one, then, out of its seven strongest other cards, the
  four with the most power weighted by plusses under the weakest-line rule,
  avoiding injured Players. It values a plus at about what one is worth in a
  match. A thinker that also tried to predict this week's pick shares from
  last week's did *worse* (ADR-092): the pick factor is hard to game, which is
  the "no pick stays best" goal at work.
- **A plus in each line.** Midfield decides who gets each chance and attack is
  individual (the drawn shooter's own attack sets the goal chance), while
  outfield defence is averaged and shares a shot's resistance with the keeper.
  The line values and the defence weight are set so one plus is worth about
  the same win chance in every line; the shape table above shows how close.
- **The per-match odds** are a closed-form estimate. The calibration table shows
  how well it matches what actually happens.
- **Auto squads** are sized to lose early but not every time; the auto-factor
  choice sits between the "beats a picked squad" and "reaches the last four"
  rows.
`;

export function renderTuningReport(stats: SimStats, targets: Target[], seconds: number): string {
  const o = stats.options;
  const lines: string[] = [];
  lines.push("# Midweek Madness — tuning report");
  lines.push("");
  lines.push(
    "Generated by `npm run sim:midweek` (`tests/sim/midweek.sim.ts`). **Do not edit by hand:** a full run " +
      "rewrites this file. It is the tuning sign-off artifact of BUILD_SPEC §44.12 (ADR-089, ADR-090); the " +
      "owner signs off the values below before any Midweek schema work.",
  );
  lines.push("");
  lines.push(
    `Run: ${o.seasons.toLocaleString("en-GB")} seasons × ${o.weeksPerSeason} weeks, seed ${o.seed}, ` +
      `${stats.matchCount.toLocaleString("en-GB")} bracket matches, ${Math.round(seconds)} s.`,
  );
  lines.push("");
  lines.push("## Targets");
  lines.push("");
  lines.push("| Target | Goal | Simulated | Pass |");
  lines.push("|---|---|---|---|");
  for (const t of targets)
    lines.push(`| ${t.name} | ${t.goal} | ${t.value} | ${t.pass ? "yes" : "**no**"} |`);
  lines.push("");
  lines.push(
    "For information: the strongest collection beats the weakest collection that fields five real " +
      `cards (no trialists) ${pct(stats.strongBeatsWeakFull)} of the time.`,
  );
  lines.push("");
  lines.push("## Squad shape (ADR-116)");
  lines.push("");
  lines.push(
    "Each archetype's plusses per line are the engine's input; a line's value for 0 / 1 / 2 / 3 plusses " +
      "and the weakest-line rule are in the tuned values below.",
  );
  lines.push("");
  lines.push("| Archetype | Attack | Midfield | Defence |");
  lines.push("|---|---:|---:|---:|");
  for (const archetype of ARCHETYPES) {
    const [att, mid, def] = MIDWEEK.shape.plusses[archetype];
    lines.push(`| ${ARCHETYPE_LABELS[archetype]} | ${att} | ${mid} | ${def} |`);
  }
  lines.push("");
  lines.push(
    "At equal power, both sides with a Goalkeeper in goal, against four All-rounders " +
      `(${stats.shape.matches.toLocaleString("en-GB")} matches each):`,
  );
  lines.push("");
  lines.push("| Outfield four | Wins |");
  lines.push("|---|---:|");
  for (const b of stats.shape.balanced) lines.push(`| ${b.squad} (balanced) | ${pct(b.rate)} |`);
  for (const b of stats.shape.stacks) lines.push(`| four × ${b.squad} (stack) | ${pct(b.rate)} |`);
  lines.push("");
  lines.push(
    "One extra plus on one All-rounder adds, in win chance: " +
      (["attack", "midfield", "defence"] as const)
        .map((line, i) => `${line} ${(stats.shape.onePlus[i] * 100).toFixed(1)} points`)
        .join(", ") +
      ". Without a Goalkeeper (an All-rounder standing in) the same four win " +
      `${pct(stats.shape.keeperlessVsKeeper)} against the side with one.`,
  );
  lines.push("");
  lines.push("## Tuned values");
  lines.push("");
  lines.push("| Knob | Starting value (§44) | Tuned |");
  lines.push("|---|---|---|");
  for (const [name, start, now] of STARTING) lines.push(`| ${name} | ${start} | ${now()} |`);
  lines.push("");
  lines.push("## How matches play");
  lines.push("");
  lines.push(`- Goals per bracket match: ${stats.goalsPerMatch.toFixed(2)}`);
  lines.push(`- Chances per match: ${stats.chancesPerMatch.toFixed(2)}`);
  lines.push(`- Matches settled on penalties: ${pct(stats.shootoutRate)}`);
  lines.push(
    `- Keeper goals per 20-week season, club-wide: ${stats.keeperGoalsPerSeason.toFixed(2)}`,
  );
  lines.push(`- Brier score of the published pre-match odds: ${stats.brier.toFixed(4)}`);
  lines.push("");
  lines.push("Calibration of the published pre-match odds:");
  lines.push("");
  lines.push("| Predicted win chance | Matches | Mean predicted | Actual |");
  lines.push("|---|---:|---:|---:|");
  stats.calibration.forEach((bucket, i) => {
    if (bucket.n === 0) return;
    lines.push(
      `| ${i * 10}–${i * 10 + 10}% | ${bucket.n.toLocaleString("en-GB")} | ${pct(bucket.predicted)} | ${pct(bucket.actual)} |`,
    );
  });
  lines.push("");
  lines.push("## Coins per member per season, by manager habit");
  lines.push("");
  lines.push("Habits are assigned at random each season, so collections average out.");
  lines.push("");
  lines.push("| Manager | Coins per 20-week season |");
  lines.push("|---|---:|");
  for (const habit of [...HABITS, "thoughtful", "auto"] as const) {
    lines.push(`| ${habit.replace("_", " ")} | ${Math.round(stats.habitMeans.get(habit) ?? 0)} |`);
  }
  lines.push("");
  lines.push("## The simulated club");
  lines.push("");
  lines.push(
    `- ${o.world.rosterSize} Players, most of them low-rated (tier weights 8 / 7 / 6 / 5 / 3 / 1 from ` +
      "Common to Elite). Seven are claimed and keep the archetype their member chose: two Goalkeepers and " +
      "one of each other specialist.",
  );
  lines.push(
    `- ${o.rotation.mode === "off" ? "No rotation" : `The other ${o.world.rosterSize - 7} rotate (\`${o.rotation.mode}\`, ADR-110)`}: ` +
      "before each week opens, each draws one of the seven archetypes, and the week plays what it drew.",
  );
  lines.push(
    `- ${o.world.members} members. Each holds a 3-card starter pack plus 0–${o.world.maxPacks - 1} packs ` +
      "(skewed: most own few), every card drawn with the pack's rarity weights 100 / 60 / 30 / 12 / 4 / 1.",
  );
  lines.push(`- Each week a Player is injured with probability ${pct(o.injuryRate)}.`);
  lines.push(
    `- ${pct(o.autoShare)} of members don't pick (auto squads). The rest follow one habit all season: ` +
      "highest OVR, least popular last week, last week's finalists' Players, random, or thought-through.",
  );
  lines.push(
    '- "Strongest" and "weakest" collections rank members by the mean OVR of their five best distinct ' +
      "Players, counting a missing Player as a trialist at 30. Both play a thought-through five when measured.",
  );
  lines.push("");
  lines.push(NOTES);
  return `${lines.join("\n")}\n`;
}
