import { MIDWEEK, PPM } from "@/game/midweek/config";
import { HABITS, type SimStats, type Target } from "./midweek-world";

/**
 * Renders docs/archive/MIDWEEK_TUNING.md, the tuning sign-off artifact
 * (BUILD_SPEC §44.12). It is regenerated by every full `npm run sim:midweek`,
 * so anything that should survive a regeneration lives here, not in the file.
 */

const x = (ppm: number) => (ppm / PPM).toFixed(3);
const pct = (v: number) => `${(v * 100).toFixed(1)}%`;

const STARTING: Array<[string, string, () => string]> = [
  ["OVR factor at OVR 83", "1.35", () => x(MIDWEEK.ovr.factorMaxPpm)],
  [
    "Form roll range (mode 1.00)",
    "0.75–1.45",
    () => `${x(MIDWEEK.form.minPpm)}–${x(MIDWEEK.form.maxPpm)}`,
  ],
  [
    "Pick factor curve",
    "(0, 1.30) (0.40, 1.00) (1, 0.85)",
    () => MIDWEEK.pick.points.map(([s, f]) => `(${x(s)}, ${x(f)})`).join(" "),
  ],
  ["Day roll", "±0.10", () => `±${x(MIDWEEK.dayRollSpreadPpm)}`],
  ["Injured fitness", "0.95", () => x(MIDWEEK.injuredFitnessPpm)],
  ["Auto-squad factor", "0.65", () => x(MIDWEEK.autoFactorPpm)],
  ["Trialist OVR", "30", () => String(MIDWEEK.trialist.ovr)],
  ["Trialist factor (new)", "—", () => x(MIDWEEK.trialist.factorPpm)],
  ["Line-shape scale per 10 offset points", "0.50", () => x(MIDWEEK.shape.scalePpm)],
  ["Keeperless keeper factor", "0.60", () => x(MIDWEEK.keeperlessFactorPpm)],
  ["Shoot-out sudden-death cap", "20", () => String(MIDWEEK.penalties.maxSuddenDeathRounds)],
  [
    "Chance slots × chance rate (new)",
    "—",
    () => `${MIDWEEK.match.chanceSlots} × ${x(MIDWEEK.match.chanceRatePpm)}`,
  ],
  [
    "Midfield / finishing contrast (new)",
    "—",
    () => `${MIDWEEK.match.midfieldContrast} / ${MIDWEEK.match.finishingContrast}`,
  ],
  ["Goal base probability (new)", "—", () => x(MIDWEEK.match.goalBasePpm)],
  ["Win-chance contrast (new)", "—", () => String(MIDWEEK.winChanceContrast)],
];

const NOTES = `## Trade-offs for the sign-off

**Signed off 2026-09-25 (ADR-092):** the owner accepted both rows that pull
against each other as they are, so their bands now pass at the tuned values.

- **Wealth against thinking.** The first and third rows pull against each other. Every
  lever that makes the strongest collection win less often against the weakest
  (flatter OVR, a bigger day roll, fewer or softer contrasts) also shrinks the
  edge a thought-through five has over a random five from the same collection.
  The weakest collection in a KUT-shaped club is almost always a starter pack:
  three cards and two trialists. Trialists cannot be made stronger, because an
  empty slot must never beat the worst real card. Along the frontier the
  simulation found, one point off the first row costs about one point of the
  third.
- **What a "thought-through" pick is.** The simulated thinker fields a
  Goalkeeper if it owns one, then its best OVR, avoiding injured Players. A
  thinker that also tried to predict this week's pick shares from last week's
  did *worse*: the pick factor is hard to game, which is the "no pick stays
  best" goal at work.
- **The per-match odds** are a closed-form estimate. The calibration table shows
  how well it matches what actually happens.
- **Auto squads** are sized to lose early but not every time; the auto-factor
  choice sits between the "beats a picked squad" and "reaches the last four"
  rows.
`;

export function renderTuningReport(stats: SimStats, targets: Target[], seconds: number): string {
  const o = stats.options;
  const lines: string[] = [];
  lines.push("# Midweek Madness — tuning report");
  lines.push("");
  lines.push(
    "Generated by `npm run sim:midweek` (`tests/sim/midweek.sim.ts`). **Do not edit by hand:** a full run " +
      "rewrites this file. It is the tuning sign-off artifact of BUILD_SPEC §44.12 (ADR-089, ADR-090); the " +
      "owner signs off the values below before any Midweek schema work.",
  );
  lines.push("");
  lines.push(
    `Run: ${o.seasons.toLocaleString("en-GB")} seasons × ${o.weeksPerSeason} weeks, seed ${o.seed}, ` +
      `${stats.matchCount.toLocaleString("en-GB")} bracket matches, ${Math.round(seconds)} s.`,
  );
  lines.push("");
  lines.push("## Targets");
  lines.push("");
  lines.push("| Target | Goal | Simulated | Pass |");
  lines.push("|---|---|---|---|");
  for (const t of targets)
    lines.push(`| ${t.name} | ${t.goal} | ${t.value} | ${t.pass ? "yes" : "**no**"} |`);
  lines.push("");
  lines.push(
    "For information: the strongest collection beats the weakest collection that fields five real " +
      `cards (no trialists) ${pct(stats.strongBeatsWeakFull)} of the time.`,
  );
  lines.push("");
  lines.push("## Tuned values");
  lines.push("");
  lines.push("| Knob | Starting value (§44) | Tuned |");
  lines.push("|---|---|---|");
  for (const [name, start, now] of STARTING) lines.push(`| ${name} | ${start} | ${now()} |`);
  lines.push("");
  lines.push("## How matches play");
  lines.push("");
  lines.push(`- Goals per bracket match: ${stats.goalsPerMatch.toFixed(2)}`);
  lines.push(`- Chances per match: ${stats.chancesPerMatch.toFixed(2)}`);
  lines.push(`- Matches settled on penalties: ${pct(stats.shootoutRate)}`);
  lines.push(
    `- Keeper goals per 20-week season, club-wide: ${stats.keeperGoalsPerSeason.toFixed(2)}`,
  );
  lines.push(`- Brier score of the published pre-match odds: ${stats.brier.toFixed(4)}`);
  lines.push("");
  lines.push("Calibration of the published pre-match odds:");
  lines.push("");
  lines.push("| Predicted win chance | Matches | Mean predicted | Actual |");
  lines.push("|---|---:|---:|---:|");
  stats.calibration.forEach((bucket, i) => {
    if (bucket.n === 0) return;
    lines.push(
      `| ${i * 10}–${i * 10 + 10}% | ${bucket.n.toLocaleString("en-GB")} | ${pct(bucket.predicted)} | ${pct(bucket.actual)} |`,
    );
  });
  lines.push("");
  lines.push("## Coins per member per season, by manager habit");
  lines.push("");
  lines.push("Habits are assigned at random each season, so collections average out.");
  lines.push("");
  lines.push("| Manager | Coins per 20-week season |");
  lines.push("|---|---:|");
  for (const habit of [...HABITS, "thoughtful", "auto"] as const) {
    lines.push(`| ${habit.replace("_", " ")} | ${Math.round(stats.habitMeans.get(habit) ?? 0)} |`);
  }
  lines.push("");
  lines.push("## The simulated club");
  lines.push("");
  lines.push(
    `- ${o.world.rosterSize} Players, most of them low-rated (tier weights 8 / 7 / 6 / 5 / 3 / 1 from ` +
      "Common to Elite), about 80% All-rounders, two Goalkeepers and one of each other specialist.",
  );
  lines.push(
    `- ${o.world.members} members. Each holds a 3-card starter pack plus 0–${o.world.maxPacks - 1} packs ` +
      "(skewed: most own few), every card drawn with the pack's rarity weights 100 / 60 / 30 / 12 / 4 / 1.",
  );
  lines.push(`- Each week a Player is injured with probability ${pct(o.injuryRate)}.`);
  lines.push(
    `- ${pct(o.autoShare)} of members don't pick (auto squads). The rest follow one habit all season: ` +
      "highest OVR, least popular last week, last week's finalists' Players, random, or thought-through.",
  );
  lines.push(
    '- "Strongest" and "weakest" collections rank members by the mean OVR of their five best distinct ' +
      "Players, counting a missing Player as a trialist at 30. Both play a thought-through five when measured.",
  );
  lines.push("");
  lines.push(NOTES);
  return `${lines.join("\n")}\n`;
}
