import { createHash } from "node:crypto";
import { ARCHETYPE_LABELS } from "@/game/archetypes";
import { PPM } from "@/game/midweek/config";
import { seedHash, shaRng } from "@/game/midweek/rng";
import { lockAt, revealAt } from "@/game/midweek/schedule";
import {
  simulateTournament,
  type EntrantInput,
  type SimulatedTournament,
} from "@/game/midweek/tournament";
import { getRarityTier } from "@/game/rating-engine";
import { reportInput, type Directory } from "@/lib/midweek/report/from-engine";
import { renderMatchReport } from "@/lib/midweek/report/render";
import type { MatchReport } from "@/lib/midweek/report/types";
import { generateWorld } from "./midweek-world";

/**
 * A sample tournament with rendered reports, as input for the Midweek design
 * pass (the pages in PRs 7–8). Every name is invented; nothing here is a real
 * member or Player. Regenerate with `node scripts/midweek/sample.mjs`.
 */

const PLAYER_NAMES = [
  "Anouk B.",
  "Bas V.",
  "Chris D.",
  "Daan K.",
  "Esther M.",
  "Floor J.",
  "Gijs H.",
  "Hidde P.",
  "Iris W.",
  "Jesse T.",
  "Kees R.",
  "Lotte S.",
  "Mo A.",
  "Noor E.",
  "Olaf G.",
  "Pim L.",
  "Quinten Z.",
  "Roos N.",
  "Sem O.",
  "Tess F.",
  "Umut C.",
  "Vera I.",
  "Wout Y.",
  "Xandra U.",
  "Yara Q.",
  "Zeger X.",
  "Ayla D.",
  "Bram K.",
  "Carmen P.",
  "Dirk S.",
];
const MANAGER_NAMES = [
  "Sanne",
  "Joris",
  "Mila",
  "Thijs",
  "Lieke",
  "Ruben",
  "Fleur",
  "Koen",
  "Nina",
  "Stijn",
  "Eline",
  "Maarten",
  "Julia",
  "Wessel",
  "Anna",
  "Tim",
  "Sophie",
  "Rick",
  "Laura",
  "Niels",
  "Emma",
  "Bart",
];

export const SAMPLE_WEEK = "2026-10-05";

export function buildSample() {
  const world = generateWorld(20261007);
  const injured = new Set(["p04", "p17"]);
  const entrants: EntrantInput[] = world.members.map((member, i) => {
    const owned = member.owned.map((card) => ({ ...card, injured: injured.has(card.playerId) }));
    const distinct = [...new Map(owned.map((c) => [c.playerId, c])).values()].sort(
      (a, b) => b.ovr - a.ovr,
    );
    // A third don't pick (auto squads); the rest pick their best five, one of them only four.
    const saved = i % 3 === 2 ? [] : distinct.slice(0, i === 4 ? 4 : 5);
    return { userId: member.userId, owned, saved };
  });

  const seed = createHash("sha256").update("midweek-sample").digest("hex");
  const hash = seedHash(seed);
  const tournament = simulateTournament(shaRng(seed), entrants) as SimulatedTournament;
  const directory: Directory = {
    player: (id) => PLAYER_NAMES[Number(id.slice(1))],
    manager: (id) => MANAGER_NAMES[Number(id.slice(1))],
  };
  const lock = lockAt(SAMPLE_WEEK);
  const reports = tournament.matches.map((match) => ({
    round: match.round,
    pairing: match.pairing,
    managers: match.userIds.map(directory.manager),
    revealAt: revealAt(lock, match.round).toISOString(),
    report: renderMatchReport(reportInput(tournament, match, hash, directory)),
  }));

  return {
    note:
      "Invented sample for the Midweek Madness design pass. Generated by scripts/midweek/sample.mjs " +
      "from the real engine and renderer; no real members or Players.",
    weekStart: SAMPLE_WEEK,
    lockAt: lock.toISOString(),
    seedHash: hash,
    seed,
    rounds: tournament.rounds,
    size: tournament.size,
    champion: directory.manager(tournament.championUserId),
    entries: tournament.entries.map((entry) => ({
      manager: directory.manager(entry.userId),
      auto: entry.auto,
      keeperless: entry.keeperless,
      cards: entry.cards.map((card, slot) => ({
        name: card.playerId === null ? null : directory.player(card.playerId),
        trialist: card.trialist,
        injured: card.injured,
        inGoal: slot === entry.keeperSlot,
        ovr: card.ovr,
        rarity: card.trialist ? null : getRarityTier(card.ovr),
        archetype: ARCHETYPE_LABELS[card.archetype],
        powerPpm: card.powerPpm,
        formRollPpm: card.formRollPpm,
        pickFactorPpm: card.pickFactorPpm,
      })),
    })),
    byes: tournament.byes.map((bye) => directory.manager(bye.userId)),
    payouts: tournament.payouts.map((p) => ({
      manager: directory.manager(p.userId),
      round: p.round,
      amount: p.amount,
      bye: p.bye,
    })),
    pickShares: tournament.pickShares
      .filter((share) => share.picks > 0)
      .map((share) => ({
        player: directory.player(share.playerId),
        picks: share.picks,
        owners: share.owners >= 3 ? share.owners : null,
        pickFactor: share.pickFactorPpm / PPM,
      })),
    matches: reports,
  };
}

function reportMarkdown(managers: string[], round: number, report: MatchReport): string[] {
  const lines = [
    `### Round ${round}: ${managers[0]} v ${managers[1]}`,
    "",
    `**${report.headline}** (${report.score})`,
    "",
  ];
  for (const fact of report.facts) lines.push(`- _${fact.text}_`);
  if (report.facts.length) lines.push("");
  for (const item of report.timeline) {
    lines.push(`- **${item.minute}'** ${item.text} _(${item.score[0]}–${item.score[1]})_`);
  }
  if (report.shootout) {
    lines.push("", "Penalties:");
    for (const line of report.shootout.lines) lines.push(`- ${line}`);
  }
  lines.push("", "Why:", "");
  report.why.forEach((side) => {
    lines.push(
      `- ${side.manager}${side.auto ? " (auto squad)" : ""}, ${Math.round(side.winChancePpm / 10_000)}% before kick-off: ` +
        side.cards
          .map(
            (c) =>
              `${c.name}${c.inGoal ? " (in goal)" : ""} ${(c.powerPpm / PPM).toFixed(2)} ` +
              `[OVR ${c.ovr}, form ${(c.formRollPpm / PPM).toFixed(2)}, pick ${(c.pickFactorPpm / PPM).toFixed(2)}` +
              `${c.injured ? ", injured" : ""}${c.pickLabel ? `, ${c.pickLabel}` : ""}]`,
          )
          .join("; "),
    );
  });
  lines.push("");
  return lines;
}

export function sampleMarkdown(sample: ReturnType<typeof buildSample>): string {
  const lines = [
    "# Midweek Madness — sample tournament",
    "",
    `${sample.note} Champion: **${sample.champion}**. ${sample.entries.length} entrants, ` +
      `${sample.rounds} rounds, byes for ${sample.byes.join(", ")}.`,
    "",
  ];
  for (const match of sample.matches)
    lines.push(...reportMarkdown(match.managers, match.round, match.report));
  return `${lines.join("\n")}\n`;
}
