import {
  HABITS,
  NO_ROTATION,
  OBSERVED_WEEKS,
  type Rotation,
  type SimStats,
  type SquadGroup,
  type Target,
} from "./midweek-world";

/**
 * Renders sim-output/MIDWEEK_ROTATION.md (gitignored), the C0 harness report for the
 * weekly archetype rotation (MM 2.0, checkpoints Q8 and Q9). It is regenerated
 * by every full `node scripts/midweek/rotation.mjs`, so anything that should
 * survive a regeneration lives here, not in the file.
 */

export type RotationVariant = { name: string; label: string; rotation: Rotation };

export const ROTATION_VARIANTS: RotationVariant[] = [
  { name: "off", label: "No rotation (today)", rotation: NO_ROTATION },
  {
    name: "uniform",
    label: "Weekly, each rotating Player draws any of the seven archetypes (the roadmap decision)",
    rotation: { mode: "uniform", keeperQuota: null, everyWeeks: 1 },
  },
  {
    name: "deal",
    label: "Weekly, the seven archetypes dealt out evenly over the rotating Players",
    rotation: { mode: "deal", keeperQuota: null, everyWeeks: 1 },
  },
  {
    name: "quota3",
    label: "Weekly, exactly three rotating Goalkeepers, the rest drawn from the other six",
    rotation: { mode: "uniform", keeperQuota: 3, everyWeeks: 1 },
  },
  {
    name: "quota1",
    label: "Weekly, exactly one rotating Goalkeeper, the rest drawn from the other six",
    rotation: { mode: "uniform", keeperQuota: 1, everyWeeks: 1 },
  },
  {
    name: "every4",
    label: "Every four weeks, each rotating Player draws any of the seven archetypes",
    rotation: { mode: "uniform", keeperQuota: null, everyWeeks: 4 },
  },
];

export type RotationRun = { variant: RotationVariant; stats: SimStats; targets: Target[] };

const pct = (v: number) => (Number.isNaN(v) ? "—" : `${(v * 100).toFixed(1)}%`);

function total(histogram: Map<number, number>): number {
  return [...histogram.values()].reduce((sum, n) => sum + n, 0);
}

function share(histogram: Map<number, number>, test: (value: number) => boolean): number {
  const all = total(histogram);
  let hits = 0;
  for (const [value, n] of histogram) if (test(value)) hits += n;
  return all === 0 ? NaN : hits / all;
}

function mean(histogram: Map<number, number>): number {
  let sum = 0;
  for (const [value, n] of histogram) sum += value * n;
  return sum / total(histogram);
}

/** The smallest value with at least `q` of the weight at or below it. */
function quantile(histogram: Map<number, number>, q: number): number {
  const all = total(histogram);
  let seen = 0;
  for (const value of [...histogram.keys()].sort((a, b) => a - b)) {
    seen += histogram.get(value)!;
    if (seen >= q * all) return value;
  }
  return NaN;
}

function table(header: string[], rows: string[][], numericFrom = 1): string[] {
  const align = header.map((_, i) => (i >= numericFrom ? "---:" : "---"));
  return [
    `| ${header.join(" | ")} |`,
    `|${align.join("|")}|`,
    ...rows.map((row) => `| ${row.join(" | ")} |`),
  ];
}

const GROUPS: Array<[SquadGroup, string]> = [
  ["thoughtful", "Thought-through"],
  ["habit", "Fixed habits"],
  ["auto", "Auto squads"],
];

export function renderRotationReport(runs: RotationRun[], seconds: number): string {
  const o = runs[0].stats.options;
  const names = runs.map((run) => `\`${run.variant.name}\``);
  const lines: string[] = [];
  const push = (...more: string[]) => lines.push(...more);

  push("# Midweek Madness — archetype rotation report");
  push("");
  push(
    "Generated by `node scripts/midweek/rotation.mjs` (`tests/sim/midweek-rotation.sim.ts`). **Do not " +
      "edit by hand:** a full run rewrites this file. It is the C0 harness report of MM 2.0 for the weekly " +
      "rotation of unclaimed Players' archetypes (ROADMAP, owner decisions 2026-09-30): the evidence for " +
      "checkpoints Q8 (smooth the keeper count?) and Q9 (a rotating archetype shows a Player is unclaimed). " +
      "It decides neither. The engine and its tuning are unchanged; only the simulated club rotates.",
  );
  push("");
  push(
    `Run: every variant over the same ${o.seasons.toLocaleString("en-GB")} seasons × ${o.weeksPerSeason} ` +
      `weeks, seed ${o.seed}, ${Math.round(seconds)} s in all. Collections, habits, injuries and the ` +
      "week's dice are identical across variants; only archetypes differ.",
  );
  push("");
  push("## The simulated club and the rotation");
  push("");
  push(
    `- The tuning club (\`MIDWEEK_TUNING.md\`, from \`npm run sim:midweek\`): ${o.world.rosterSize} Players, ${o.world.members} ` +
      "members. Its seven specialists (two Goalkeepers, one each of Speedster, Finisher, Playmaker, " +
      "Defender, Tank) are the **claimed** Players: their members chose the archetype, and claiming ends " +
      `the rotation. The other ${o.world.rosterSize - 7} are unclaimed All-rounders, about 80% of the ` +
      "roster, and every one of them is active and collectible, so all of them rotate.",
  );
  push(
    "- The rotation runs before each week opens and the week plays what it set, as the ADR-099 snapshot " +
      "freezes it. It is seeded and deterministic (a hash of seed, season, rotation period and Player), " +
      "and a card always carries its Player's archetype of the week.",
  );
  push(
    '- The "thought-through" manager sees the week\'s archetypes, as the picker does, and fields its ' +
      "best Goalkeeper if it owns one. The fixed habits ignore archetypes.",
  );
  push("");
  push(
    ...table(
      ["Variant", "Rotation"],
      runs.map((run) => [`\`${run.variant.name}\``, run.variant.label]),
    ),
  );
  push("");

  push("## ADR-092 targets");
  push("");
  push(
    "The three signed-off rows first: strongest vs weakest at most 72%, thought-through vs random at " +
      "least 58%, no fixed habit ahead by more than 5%. **Bold** misses its band.",
  );
  push("");
  const targetRows = runs[0].targets.map((target, i) => [
    target.name,
    ...runs.map((run) =>
      run.targets[i].pass ? run.targets[i].value : `**${run.targets[i].value}**`,
    ),
  ]);
  const signedOff = [0, 2, 3];
  push(
    ...table(
      ["Target", ...names],
      [
        ...signedOff.map((i) => targetRows[i]),
        ...targetRows.filter((_, i) => !signedOff.includes(i)),
      ],
    ),
  );
  push("");
  push(
    ...table(
      ["For information", ...names],
      [
        [
          "Strongest vs the weakest with five real cards",
          ...runs.map((run) => pct(run.stats.strongBeatsWeakFull)),
        ],
        ["Goals per bracket match", ...runs.map((run) => run.stats.goalsPerMatch.toFixed(2))],
        ["Matches settled on penalties", ...runs.map((run) => pct(run.stats.shootoutRate))],
        ["Brier score of the published odds", ...runs.map((run) => run.stats.brier.toFixed(4))],
      ],
    ),
  );
  push("");
  push("Coins per member per 20-week season, by manager habit:");
  push("");
  push(
    ...table(
      ["Manager", ...names],
      [...HABITS, "thoughtful", "auto"].map((habit) => [
        habit.replace("_", " "),
        ...runs.map((run) => String(Math.round(run.stats.habitMeans.get(habit as never) ?? 0))),
      ]),
    ),
  );
  push("");

  push("## Keepers (Q8)");
  push("");
  push(
    "A squad without a Goalkeeper puts its best defender in goal at ×0.45 of a keeper's strength, so the " +
      "number of Goalkeepers in play is what the rotation swings most.",
  );
  push("");
  const maxRoster = Math.max(...runs.flatMap((run) => [...run.stats.keepers.roster.keys()]));
  push("Goalkeepers on the whole roster in a week (claimed and rotating):");
  push("");
  push(
    ...table(
      ["", ...names],
      [
        ["Mean", ...runs.map((run) => mean(run.stats.keepers.roster).toFixed(2))],
        ...Array.from({ length: maxRoster + 1 }, (_, k) => [
          `${k}`,
          ...runs.map((run) => {
            const s = share(run.stats.keepers.roster, (v) => v === k);
            return s === 0 ? "·" : pct(s);
          }),
        ]),
      ],
    ),
  );
  push("");
  push("What members and squads hold, per member-week and per entered squad:");
  push("");
  const squadRows: string[][] = [
    [
      "Members owning at least one Goalkeeper",
      ...runs.map((run) => pct(run.stats.keepers.memberOwnsKeeper)),
    ],
    [
      `Members owning one in a week, of ${o.world.members}: middle 80% of weeks`,
      ...runs.map((run) => {
        const h = run.stats.keepers.membersOwningKeeper;
        return `${quantile(h, 0.1)}–${quantile(h, 0.9)}`;
      }),
    ],
    [
      `… and in the leanest 1% of weeks, at most`,
      ...runs.map((run) => String(quantile(run.stats.keepers.membersOwningKeeper, 0.01))),
    ],
    [
      "Entered squads without a Goalkeeper (all)",
      ...runs.map((run) => pct(run.stats.keepers.bracketKeeperless)),
    ],
  ];
  for (const [group, label] of GROUPS) {
    squadRows.push([
      `${label}: no Goalkeeper`,
      ...runs.map((run) => pct(run.stats.keepers.keeperless.get(group)!)),
    ]);
    squadRows.push([
      `${label}: two or more Goalkeepers`,
      ...runs.map((run) => pct(share(run.stats.keepers.squads.get(group)!, (v) => v >= 2))),
    ]);
  }
  push(...table(["", ...names], squadRows));
  push("");

  push("## How visibly rotation marks a Player as unclaimed (Q9)");
  push("");
  push(
    "A member who watches archetypes week to week can tell a rotating Player from a fixed one. Claimed " +
      "Players never change here; in the club a member may change their own at most once every 14 days " +
      "(ADR-094), which is the only noise an observer would have to see through.",
  );
  push("");
  push(
    ...table(
      ["", ...names],
      [
        [
          "A rotating Player's archetype changes from one week to the next",
          ...runs.map((run) => pct(run.stats.visibility.weeklyChangeRotating)),
        ],
        ...OBSERVED_WEEKS.map((weeks) => [
          `A rotating Player has visibly changed within ${weeks} weeks`,
          ...runs.map((run) => pct(run.stats.visibility.spottedAfter.get(weeks)!)),
        ]),
        [
          "Shows All-rounder this week → unclaimed",
          ...runs.map((run) => pct(run.stats.visibility.unclaimedGivenAllRounder)),
        ],
        [
          "Shows another archetype this week → unclaimed",
          ...runs.map((run) => pct(run.stats.visibility.unclaimedGivenSpecialist)),
        ],
      ],
    ),
  );
  push("");
  push(
    "The last two rows are what one week's archetype alone gives away. In this club no claimed Player " +
      "is an All-rounder, so today the default marks every unclaimed Player and a specialist is always " +
      "claimed; in the real club some members keep the default, which blurs both rows without changing " +
      "the history rows. Rotation swaps the one-week signal for a history signal: a Player whose " +
      "archetype keeps changing is unclaimed.",
  );
  return `${lines.join("\n")}\n`;
}
